FloatLayout:
    on_touch_down: app.touch_down_handler(*args)
    Image:
        id: monster_image
        size_hint: (0.15, 0.15)
        pos_hint: {'x': 0.8, 'y': 0.8}
        source: "10.png"
        im_num: 10
        allow_stretch: True
        on_im_num: app.change_monst_im()
        on_pos_hint: app.monst_pos_hint()
    Image:
        id: character_image
        size_hint: (0.15, 0.15)
        pos_hint: {'x': 0.2, 'y': 0.4}
        allow_stretch: True
        source: "0.png"
        im_num: 0
        on_im_num: app.change_char_im()
